services:
  build:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    command: bash scripts/build.sh

  test:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./config:/app/config
      - ./scripts:/app/scripts
    command: bash scripts/test.sh

  upload:
    build:
      context: .
    volumes:
      - ./src:/app/src        # Ensure src is properly mounted
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    command: bash scripts/upload.sh
